[book]
authors = ["shutosha"]
language = "en"
src = "src"
title = "deepDive"
description = "A deep dive into various topics with Gemini."

[build]
create-missing = false

[preprocessor.katex]

[output.html]
theme = "theme"
additional-css = ["theme/custom.css"]
cname = "deepdive.shutri.com"
no-section-label = true
